CREATE TABLE datawarehouse.factorderlines (
  PRODUCTID INTEGER NOT NULL,
  CUSTOMERID INTEGER NOT NULL,
  DATEID VARCHAR(8) NOT NULL,
  ORDERNUMBER VARCHAR(50) NOT NULL,
  ORDERLINENUMBER INTEGER NOT NULL,
  DEALSIZE VARCHAR(10) NOT NULL,
  QUANTITYORDERED INTEGER NOT NULL,
  PRICEEACH NUMERIC(10,2) NOT NULL,
  SALES NUMERIC(10,2) NOT NULL,
  TOTAL_ORDERLINE_AMOUNT NUMERIC(10,2) NOT NULL,
  --PRIMARY KEY (PRODUCTID, CUSTOMERID, DATEID, ORDERNUMBER, ORDERLINENUMBER),
  FOREIGN KEY (PRODUCTID) REFERENCES datawarehouse.dim_product (PRODUCTID),
  FOREIGN KEY (CUSTOMERID) REFERENCES datawarehouse.dim_customer (CUSTOMERID),
  FOREIGN KEY (DATEID) REFERENCES datawarehouse.dim_date (DATEID)
);

-- Create fact table factorders
CREATE TABLE datawarehouse.factorders (
  CUSTOMERID INTEGER NOT NULL,
  DATEID VARCHAR(8) NOT NULL,
  ORDERNUMBER VARCHAR(50) NOT NULL,
  STATUS VARCHAR(20) NOT NULL,
  TOTAL_ORDER_AMOUNT NUMERIC(10,2) NOT NULL,
  PRIMARY KEY CLUSTERED (ORDERNUMBER),
  FOREIGN KEY (CUSTOMERID) REFERENCES datawarehouse.dim_customer (CUSTOMERID),
  FOREIGN KEY (DATEID) REFERENCES datawarehouse.dim_date (DATEID)
);