-- Create fact table factorderlines = Fact_Transaction
CREATE TABLE factorderlines (
    PRODUCTID INTEGER NOT NULL,
    CUSTOMERID INTEGER NOT NULL,
    DATEID INTEGER NOT NULL,
    ORDERNUMBER VARCHAR(50) NOT NULL,
    ORDERLINENUMBER INTEGER NOT NULL,
    QUANTITYORDERED INTEGER NOT NULL,
    PRICEEACH NUMERIC(10,2) NOT NULL,
    DEALSIZE VARCHAR(10) NOT NULL,
    SALEPRICE NUMERIC(10,2) NOT NULL,
    PRIMARY KEY (PRODUCTID, CUSTOMERID, DATEID, ORDERNUMBER, ORDERLINENUMBER),
    FOREIGN KEY (PRODUCTID) REFERENCES dim_product (PRODUCTID),
    FOREIGN KEY (CUSTOMERID) REFERENCES dim_customer (CUSTOMERID),
    FOREIGN KEY (DATEID) REFERENCES dim_date (DATEID)
);

-- Create fact table factorders
CREATE TABLE factorders (
    CUSTOMERID INTEGER NOT NULL,
    DATEID INTEGER NOT NULL,
    ORDERNUMBER VARCHAR(50) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    TOTAL_ORDER_AMOUNT NUMERIC(10,2) NOT NULL,
    PRIMARY KEY (ORDERNUMBER),
    FOREIGN KEY (CUSTOMERID) REFERENCES dim_customer (CUSTOMERID),
    FOREIGN KEY (DATEID) REFERENCES dim_date (DATEID)
);
