-- How much revenue was generated by each product line and in total for each month by year?

SELECT
    dp.PRODUCTLINE,
    dd.[MONTHNUMBERBYYEAR],
    SUM(fol.TOTAL_ORDERLINE_AMOUNT) AS Revenue
FROM
    datawarehouse.factorderlines AS fol
    JOIN datawarehouse.dim_product AS dp ON fol.PRODUCTID = dp.PRODUCTID
    JOIN datawarehouse.dim_date AS dd ON fol.DATEID = dd.DATEID
WHERE dd.[MONTHNUMBERBYYEAR] IS NOT NULL
GROUP BY
    dp.PRODUCTLINE,
    dd.[MONTHNUMBERBYYEAR],
    ROLLUP(dp.PRODUCTLINE, dd.[MONTHNUMBERBYYEAR])

-- What was the total revenue generated by each product line and customer for each quarter by year?

SELECT
    dp.PRODUCTLINE,
    dc.CUSTOMERNAME,
    dd.QUARTER,
    dd.YEAR,
    SUM(fol.TOTAL_ORDERLINE_AMOUNT) AS Revenue
FROM
    datawarehouse.factorderlines fol
        JOIN datawarehouse.dim_product dp ON fol.PRODUCTID = dp.PRODUCTID
        JOIN datawarehouse.dim_customer dc ON fol.CUSTOMERID = dc.CUSTOMERID
        JOIN datawarehouse.dim_date dd ON fol.DATEID = dd.DATEID
GROUP BY
    dp.PRODUCTLINE,
    dc.CUSTOMERNAME,
    dd.QUARTER,
    dd.YEAR,
    CUBE(dp.PRODUCTLINE, dc.CUSTOMERNAME, dd.QUARTER, dd.YEAR)

-- How many orders were placed by each customer,
-- and what was the total revenue generated by them for each month of the year?
SELECT
    dc.CUSTOMERNAME,
    dd.[MONTHNUMBERBYYEAR],
    COUNT(DISTINCT fo.ORDERNUMBER) AS OrderCount,
    SUM(fol.TOTAL_ORDERLINE_AMOUNT) AS Revenue
FROM
    datawarehouse.factorders fo
        JOIN datawarehouse.factorderlines fol ON fo.ORDERNUMBER = fol.ORDERNUMBER
        JOIN datawarehouse.dim_customer dc ON fo.CUSTOMERID = dc.CUSTOMERID
        JOIN datawarehouse.dim_date dd ON fo.DATEID = dd.DATEID
GROUP BY
    dc.CUSTOMERNAME,
    dd.[MONTHNUMBERBYYEAR],
    ROLLUP(dc.CUSTOMERNAME, dd.[MONTHNUMBERBYYEAR])

